language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # Qwt
  - sudo apt-get install -qq libqwt-qt5-dev  # OCLint
  # codecov
  - sudo pip install codecov # From https://github.com/travis-ci/travis-ci/issues/1705
  # OCLint
  - ./install_oclint.sh

# Xenial
services:
  - xvfb

script: 
  - ./download_other_githubs.sh
  - ./build_other_githubs.sh
  - qmake -qt=qt5 SurfacePlotterDesktop.pro
  - make --silent
  - ./SurfacePlotterDesktop &
  - sleep 10
  - sudo killall -9 SurfacePlotterDesktop
  - ./get_code_cov.sh >/dev/null
  - codecov >/dev/null
  - ./do_oclint.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  # Download thesis
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

after_failure:
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

