language: cpp
dist: xenial
compiler: gcc

addons:
  # Boost
  apt: 
    packages: libboost-all-dev

install: 
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # Qwt
  - sudo apt-get install -qq libqwt-qt5-dev  # OCLint
  # codecov
  - sudo pip install codecov # From https://github.com/travis-ci/travis-ci/issues/1705
  # OCLint
  - ./install_oclint.sh

# Xenial
services:
  - xvfb

script: 
  - ./download_other_githubs.sh
  - ./build_other_githubs.sh
  - qmake SurfacePlotterConsole.pro
  - make --silent
  - ./SurfacePlotterConsole
  - qmake SurfacePlotterDesktop.pro
  - make --silent
  - ./SurfacePlotterDesktop &
  - sleep 10
  - sudo killall -9 SurfacePlotterDesktop
  - ./get_code_cov.sh >/dev/null
  - codecov >/dev/null
  - ./do_oclint.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
